name: build MusicFree

on:
  schedule:
    - cron: 30 1 * * *
  workflow_dispatch:
    inputs:
      rebuild:
        description: "重新构建"
        required: false
        type: boolean
env:
  commit: ""
  daytime: ""
  tag: ""
  vname: ""
  renote: ""
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - userName: maotoumao
            repoName: MusicFree
            branchName: master
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check New Commit
        run: |
          repoPath="${{ matrix.userName }}/${{ matrix.repoName }}"
          commit=$(curl -sL https://github.com/$repoPath/commits/${{ matrix.branchName }} |grep -o "/$repoPath/commit/[a-z0-9]\+" |head -1 | cut -d\/ -f5)
          if ! grep -q "$commit" README.md || [ "${{ inputs.rebuild }}" == "true" ]; then
            git clone https://github.com/$repoPath -b ${{ matrix.branchName }}
            cd ${{ matrix.repoName }}
            vname=$(git log --date=format:'%Y%m%d-%H%M' --pretty=format:%cd ${commit:0:7} -1)
            daytime=$(git log --date=format:'%Y%m%d' --pretty=format:%cd ${commit:0:7} -1)
            echo "tag=${{ matrix.userName }}_${{ matrix.repoName }}_$vname" >> $GITHUB_ENV
            echo "commit=$commit" >> $GITHUB_ENV
            echo "vname=$vname" >> $GITHUB_ENV
            echo "daytime=$daytime" >> $GITHUB_ENV
          fi

      - name: Extra Modify
        if: ${{ env.commit }}
        working-directory: ${{ matrix.repoName }}
        run: |
          sed -i 's|subscribeUrl'\'');|subscribeUrl'\'') ?? '\''[{"url":"${{ secrets.SUBSCRIB_URL }}"}]'\'';|g' src/pages/setting/settingTypes/pluginSetting/views/pluginList.tsx
          #sed -i "/versionName/s#[0-9a-zA-Z_\.\'\"-]\+\$#\'${{ env.tag }}\'#" android/app/build.gradle
          cp -f ${{ github.workspace }}/.github/workflows/normal.jks android/app/normal.jks
          echo -e 'RELEASE_STORE_FILE=./normal.jks'                   >  android/keystore.properties
          echo -e 'RELEASE_KEY_ALIAS=${{ secrets.JKS_ALIAS }}'        >> android/keystore.properties
          echo -e 'RELEASE_STORE_PASSWORD=${{ secrets.JKS_PASSWD }}'  >> android/keystore.properties
          echo -e 'RELEASE_KEY_PASSWORD=${{ secrets.JKS_PASSWD }}'    >> android/keystore.properties

      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup Gradle
        if: ${{ env.commit }}
        uses: gradle/gradle-build-action@v2

      - name: Build With Gradle
        if: ${{ env.commit }}
        working-directory: ${{ matrix.repoName }}
        run: |
          npm install
          cd android && chmod a+x gradlew
          ./gradlew app:assembleRelease && cd -

      - name: Release Note
        if: ${{ env.commit }}
        working-directory: ${{ matrix.repoName }}
        run: |
          echo "start  => 0"
          rm -rf apk && mkdir -p apk
          echo "start  => 1"
          for file in `find -name "*.apk" -print`; do
            cp "$file" apk/Music_latest.apk
            mv "$file" apk/${{ env.tag }}.apk
          done
          apkUrl="https://github.com/${{ github.repository }}/releases/download/${{ env.tag }}/${{ env.tag }}.apk"
          echo "apkUrl => $apkUrl"
          apkSize=$(stat -c%s apk/${{ env.tag }}.apk)
          lastCommit=$(grep "${{ matrix.userName }}\/${{ matrix.repoName }}" ${{ github.workspace }}/README.md |grep -o '[a-z0-9]\{40\}')
          msg=$(git log --pretty=format:'%h - %s (%cr) <%an>' --abbrev-commit --topo-order ${lastCommit}^.. |sed -e "s# \{2,\}#\n#g" -e "/^Merge \(pull\|branch\|remote\)/d" -e '/^$/d' |cat -n |sort -k2,2 -k1,1n |uniq -f1 |sort -k1,1n |cut -f2-)
          msg=$(echo "$msg" |sed ':a;N;$!ba;s/\n/<\/br>/g')
          cat android/app/build/outputs/apk/release/output-metadata.json | jq -c --arg content "$msg" --arg apkUrl "${{ secrets.SHORT_URL }}/Music" '{"pkgName": .applicationId, "versionName": .elements[0].versionName, "apkSize": "'$apkSize'","apkUrl": $apkUrl, "msg": $content | @sh}' >  apk/${{ env.tag }}-Release.txt
          renote='{"title":"[MusicFree]${{ env.vname }}","content":"下载地址: ${{ secrets.SHORT_URL }}/Music</br>github: https://github.com/${{ github.repository }}</br>提交记录:</br>'$msg'"}'
          echo "renote=$renote" >> $GITHUB_ENV

      - name: push-to-alist
        continue-on-error: true
        uses: wj2008/auto-push-alist@v1
        if: ${{ env.commit }}
        with:
          token: ${{ secrets.ALS_TOKEN }}
          upUrl: ${{ secrets.ALS_URL }}
          saveDir: "${{ secrets.ALS_DIR }}/${{ matrix.userName }}_${{ matrix.repoName }}"
          upFile: ${{ matrix.repoName }}/apk/Music_latest.apk

      - name: push-to-alist
        continue-on-error: true
        uses: wj2008/auto-push-alist@v1
        if: ${{ env.commit }}
        with:
          token: ${{ secrets.ALS_TOKEN }}
          upUrl: ${{ secrets.ALS_URL }}
          saveDir: "${{ secrets.ALS_DIR }}/${{ matrix.userName }}_${{ matrix.repoName }}"
          upFile: ${{ matrix.repoName }}/apk/${{ env.tag }}.apk

      - name: Webhook
        if: ${{ env.commit }}
        continue-on-error: true
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          headers: '{"repository": "joelwmale/webhook-action", "x-requested-id": "66fa52b9-3b8c-43bb-8660-66fa52b9"}'
          body: "${{ env.renote }}"

      - name: Upload-Artifact
        uses: actions/upload-artifact@v3
        if: ${{ env.commit }}
        with:
          name: ${{ env.tag }}
          path: |
            ${{ matrix.repoName }}/apk/*

      - name: Release-and-Upload-Assets
        uses: ncipollo/release-action@v1
        if: ${{ env.commit }}
        with:
          name: ${{ env.tag }}
          tag: ${{ env.tag }}
          bodyFile: ${{ matrix.repoName }}/apk/${{ env.tag }}-Release.txt
          allowUpdates: true
          removeArtifacts: true
          artifacts: |
            ${{ matrix.repoName }}/apk/*.apk

      - name: Push to main
        if: ${{ env.commit }}
        continue-on-error: true
        run: |
          rm -rf ${{ matrix.repoName }}
          sed -i '/url =/d' ./.git/config
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url --add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git pull --rebase
          sed -i "/${{ matrix.userName }}\/${{ matrix.repoName }}/s#Updated: [a-zA-Z0-9]*#Updated: ${{ env.commit }}#" README.md
          git add --all
          git commit -m "${{ env.commit }}"
          git push -u -f origin main