name: build SmsForwarders

on:
  schedule:
    - cron: 30 0 * * *
  workflow_dispatch:
    inputs:
      rebuild:
        description: "重新构建"
        required: false
        type: boolean
env:
  commit: ""
  daytime: ""
  tag: ""
  vname: ""
  renote: ""
  output: "${{ github.workspace }}/SmsForwarder/build/app/outputs/apk/release"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - userName: pppscn
            repoName: SmsForwarder
            branchName: main
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check New Commit
        run: |
          repoPath="${{ matrix.userName }}/${{ matrix.repoName }}"
          commit=$(curl -sL https://github.com/$repoPath/commits/${{ matrix.branchName }} |grep -o "/$repoPath/commit/[a-z0-9]\+" |head -1 | cut -d\/ -f5)
          if ! grep -q "$commit" README.md || [ "${{ inputs.rebuild }}" == "true" ]; then
            git clone https://github.com/$repoPath -b ${{ matrix.branchName }}
            cd ${{ matrix.repoName }}
            vname=$(git log --date=format:'%Y%m%d-%H%M' --pretty=format:%cd ${commit:0:7} -1)
            daytime=$(git log --date=format:'%Y%m%d' --pretty=format:%cd ${commit:0:7} -1)
            echo "tag=${{ matrix.userName }}_${{ matrix.repoName }}_$vname" >> $GITHUB_ENV
            echo "commit=$commit" >> $GITHUB_ENV
            echo "vname=$vname" >> $GITHUB_ENV
            echo "daytime=$daytime" >> $GITHUB_ENV
          fi

      - name: Extra Modify
        if: ${{ env.commit }}
        working-directory: ${{ matrix.repoName }}
        run: |
          echo '修改客制化'
          sed -i 's|http://127.0.0.1:5000|${{ secrets.SMS_WEBHOOK }}|g' app/src/main/java/com/idormy/sms/forwarder/utils/HttpServerUtils.kt
          sed -i 's|(AUTO_CHECK_UPDATE, true)|(AUTO_CHECK_UPDATE, false)|g' app/src/main/java/com/idormy/sms/forwarder/utils/SettingUtils.kt
          sed -i 's|(IS_AGREE_PRIVACY_KEY, false)|(IS_AGREE_PRIVACY_KEY, true)|g' app/src/main/java/com/idormy/sms/forwarder/utils/SettingUtils.kt
          sed -i 's|(SP_ENABLE_SMS, false)|(SP_ENABLE_SMS, true)|g' app/src/main/java/com/idormy/sms/forwarder/utils/SettingUtils.kt
          sed -i 's|"com.idormy.sms.forwarder"|"com.android.forwarder"|g' app/build.gradle
          echo '修改签名'
          signingConfigs='ICAgIHNpZ25pbmdDb25maWdzIHtcCiAgICAgICAgaWYgKHByb2plY3QuaGFzUHJvcGVydHkoIlJFTEVBU0VfU1RPUkVfRklMRSIpKSB7XAogICAgICAgICAgICBteUNvbmZpZyB7XAogICAgICAgICAgICAgICAgc3RvcmVGaWxlIGZpbGUoUkVMRUFTRV9TVE9SRV9GSUxFKVwKICAgICAgICAgICAgICAgIHN0b3JlUGFzc3dvcmQgUkVMRUFTRV9TVE9SRV9QQVNTV09SRFwKICAgICAgICAgICAgICAgIGtleUFsaWFzIFJFTEVBU0VfS0VZX0FMSUFTXAogICAgICAgICAgICAgICAga2V5UGFzc3dvcmQgUkVMRUFTRV9LRVlfUEFTU1dPUkRcCiAgICAgICAgICAgICAgICB2MVNpZ25pbmdFbmFibGVkIHRydWVcCiAgICAgICAgICAgICAgICB2MlNpZ25pbmdFbmFibGVkIHRydWVcCiAgICAgICAgICAgICAgICBlbmFibGVWM1NpZ25pbmcgPSB0cnVlXAogICAgICAgICAgICAgICAgZW5hYmxlVjRTaWduaW5nID0gdHJ1ZVwKICAgICAgICAgICAgfVwKICAgICAgICB9XAogICAgfVwKXA=='
          signingConfig='ICAgICAgICAgICAgaWYgKHByb2plY3QuaGFzUHJvcGVydHkoIlJFTEVBU0VfU1RPUkVfRklMRSIpKSB7XAogICAgICAgICAgICAgICAgc2lnbmluZ0NvbmZpZyBzaWduaW5nQ29uZmlncy5teUNvbmZpZ1wKICAgICAgICAgICAgfVwK'
          signingConfigs="$(echo "$signingConfigs" |base64 -d )"
          signingConfig="$(echo "$signingConfig" |base64 -d )"
          sed -i -e "/defaultConfig {/i\\$signingConfigs " -e "/debug {/a\\$signingConfig " -e "/release {/a\\$signingConfig " app/build.gradle
          cp -f ${{ github.workspace }}/.github/workflows/normal.jks app/normal.jks
          sed -i '$a\RELEASE_STORE_FILE=./normal.jks'     ./gradle.properties
          sed -i '$a\RELEASE_KEY_ALIAS=${{ secrets.JKS_ALIAS }}'            ./gradle.properties
          sed -i '$a\RELEASE_STORE_PASSWORD=${{ secrets.JKS_PASSWD }}'       ./gradle.properties
          sed -i '$a\RELEASE_KEY_PASSWORD=${{ secrets.JKS_PASSWD }}'         ./gradle.properties

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        if: ${{ env.commit }}
        uses: gradle/actions/setup-gradle@v3

      - name: Build With Gradle
        if: ${{ env.commit }}
        working-directory: ${{ matrix.repoName }}
        run: bash ./gradlew assembleRelease

      - name: Release Note
        if: ${{ env.commit }}
        working-directory: ${{ matrix.repoName }}
        run: |
          rm -rf apk && mkdir -p apk
          for file in `find -name "SmsF_*_arm64-v8a_release.apk" -print`; do
            cp "$file" apk/SmsF_arm64-v8a_latest.apk
            mv "$file" apk/${{ env.tag }}.apk
          done
          apkSize=$(stat -c%s apk/${{ env.tag }}.apk)
          time=$(date +%s%N)
          body='[{"apkSize":"'$apkSize'","apkPkg":"com.android.forwarder","apkVer":"${{ env.vname }}","apkUrl":"${{ secrets.SMS_URL }}?t='$time'"}]'
          curl '${{ secrets.FUCK0 }}' -H 'Content-Type: application/json' -H 'X-Requested-Id: ${{ secrets.REQUEST_ID }}' --data-raw ''$body''
          lastCommit=$(grep "${{ matrix.userName }}\/${{ matrix.repoName }}" ${{ github.workspace }}/README.md |grep -o '[a-z0-9]\{40\}')
          msg=$(git log --pretty=format:'%h - %s (%cr) <%an>' --abbrev-commit --topo-order ${lastCommit}^.. |sed -e "s# \{2,\}#\n#g" -e "/^Merge \(pull\|branch\|remote\)/d" -e '/^$/d' |cat -n |sort -k2,2 -k1,1n |uniq -f1 |sort -k1,1n |cut -f2-)
          msg=$(echo "$msg" |sed ':a;N;$!ba;s/\n/<\/br>/g')
          echo $msg >  apk/${{ env.tag }}-Release.txt
          renote='{"title":"[TVBOX]${{ env.vname }}","content":"github: https://github.com/${{ github.repository }}</br>提交记录:</br>'$msg'"}'
          echo "renote=$renote" >> $GITHUB_ENV

      - name: push-to-alist
        continue-on-error: true
        uses: wj2008/auto-push-alist@v1
        if: ${{ env.commit }}
        with:
          token: ${{ secrets.ALS_TOKEN }}
          upUrl: ${{ secrets.ALS_URL }}
          saveDir: "${{ secrets.ALS_DIR }}/${{ matrix.userName }}_${{ matrix.repoName }}"
          upFile: ${{ matrix.repoName }}/apk/SmsF_arm64-v8a_latest.apk
          
      - name: push-to-alist
        continue-on-error: true
        uses: wj2008/auto-push-alist@v1
        if: ${{ env.commit }}
        with:
          token: ${{ secrets.ALS_TOKEN }}
          upUrl: ${{ secrets.ALS_URL }}
          saveDir: "${{ secrets.ALS_DIR }}/${{ matrix.userName }}_${{ matrix.repoName }}"
          upFile: ${{ matrix.repoName }}/apk/${{ env.tag }}.apk

      - name: Webhook
        if: ${{ env.commit }}
        continue-on-error: true
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          headers: '{"repository": "joelwmale/webhook-action", "x-requested-id": "${{ secrets.REQUEST_ID }}"}'
          body: "${{ env.renote }}"

      - name: Upload-Artifact
        uses: actions/upload-artifact@v4
        if: ${{ env.commit }}
        with:
          name: ${{ env.tag }}
          path: |
            ${{ matrix.repoName }}/apk/*

      - name: Release-and-Upload-Assets
        uses: ncipollo/release-action@v1
        if: ${{ env.commit }}
        with:
          name: ${{ env.tag }}
          tag: ${{ env.tag }}
          bodyFile: ${{ matrix.repoName }}/apk/${{ env.tag }}-Release.txt
          allowUpdates: true
          removeArtifacts: true
          artifacts: |
            ${{ matrix.repoName }}/apk/*.apk

      - name: Push to main
        if: ${{ env.commit }}
        continue-on-error: true
        run: |
          rm -rf ${{ matrix.repoName }}
          sed -i '/url =/d' ./.git/config
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url --add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git pull --rebase
          sed -i "/${{ matrix.userName }}\/${{ matrix.repoName }}/s#Updated: [a-zA-Z0-9]*#Updated: ${{ env.commit }}#" README.md
          git add --all
          git commit -m "${{ env.commit }}"
          git push -u -f origin main
